language: node_js
node_js:
  - 0.8
notifications:
  email: false
before_script:
  - "export DISPLAY=:99.0" 
  - npm install connect
  - sudo node lib/server.js &
  - sleep 5
script: phantomjs lib/test/run-tests.js 'http://localhost:80/test.html'